spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:file:.\database\dashboard
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  test:
    database:
      replace: none

cron:
  expression: "*/20 * * * * *"
#  expression: "-"