spring:
  jmx:
    enabled: true
  application:
    name: smokeTestDashboard
  profiles:
    active: local

management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"
    web:
      exposure:
        include: "health,info"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

cron:
#    expression: "*/10 * * * * *"
  expression: "-"
